export const Env = {
    // 项目模式
    NODE_ENV: process.env.NODE_ENV,
    // 应用名称
    APP_NAME: process.env.APP_NAME,
    // 加密盐
    MD5_SALT: process.env.MD5_SALT,
    // 监听端口
    APP_PORT: Number(process.env.APP_PORT),
    // 监听主机
    APP_HOST: process.env.APP_HOST,
    // 超级管理员密码
    DEV_PASSWORD: process.env.DEV_PASSWORD,
    // 请求体大小 10M
    BODY_LIMIT: Number(process.env.BODY_LIMIT),
    // 是否进行参数验证
    PARAMS_CHECK: process.env.PARAMS_CHECK,
    // 日志等级
    LOG_LEVEL: process.env.LOG_LEVEL,
    LOG_EXCLUDE_FIELDS: process.env.LOG_EXCLUDE_FIELDS,
    LOG_DIR: process.env.LOG_DIR,
    LOG_TO_CONSOLE: Number(process.env.LOG_TO_CONSOLE),
    LOG_MAX_SIZE: Number(process.env.LOG_MAX_SIZE),
    // 时区
    TZ: process.env.TZ,
    // 数据库配置
    DB_ENABLE: Number(process.env.DB_ENABLE),
    // 通用数据库连接参数
    DB_TYPE: process.env.DB_TYPE, // sqlite | mysql | postgresql
    DB_HOST: process.env.DB_HOST,
    DB_PORT: Number(process.env.DB_PORT),
    DB_USER: process.env.DB_USER,
    DB_PASS: process.env.DB_PASS,
    DB_NAME: process.env.DB_NAME,
    DB_DEBUG: Number(process.env.DB_DEBUG),
    DB_POOL_MAX: Number(process.env.DB_POOL_MAX),
    // Redis配置
    REDIS_URL: process.env.REDIS_URL,
    REDIS_ENABLE: Number(process.env.REDIS_ENABLE),
    REDIS_HOST: process.env.REDIS_HOST,
    REDIS_PORT: Number(process.env.REDIS_PORT),
    REDIS_USERNAME: process.env.REDIS_USERNAME,
    REDIS_PASSWORD: process.env.REDIS_PASSWORD,
    REDIS_DB: Number(process.env.REDIS_DB),
    REDIS_KEY_PREFIX: process.env.REDIS_KEY_PREFIX,
    // JWT配置
    JWT_SECRET: process.env.JWT_SECRET,
    JWT_EXPIRES_IN: process.env.JWT_EXPIRES_IN,
    JWT_ALGORITHM: process.env.JWT_ALGORITHM,
    // 邮件配置
    MAIL_HOST: process.env.MAIL_HOST,
    MAIL_PORT: Number(process.env.MAIL_PORT),
    MAIL_POOL: process.env.MAIL_POOL,
    MAIL_SECURE: process.env.MAIL_SECURE,
    MAIL_USER: process.env.MAIL_USER,
    MAIL_PASS: process.env.MAIL_PASS,
    MAIL_SENDER: process.env.MAIL_SENDER,
    MAIL_ADDRESS: process.env.MAIL_ADDRESS,
    // 同步脚本开关（用于 core/scripts/syncDb.js）
    SYNC_MERGE_ALTER: process.env.SYNC_MERGE_ALTER,
    SYNC_ONLINE_INDEX: process.env.SYNC_ONLINE_INDEX,
    SYNC_DISALLOW_SHRINK: process.env.SYNC_DISALLOW_SHRINK,
    SYNC_ALLOW_TYPE_CHANGE: process.env.SYNC_ALLOW_TYPE_CHANGE
};
