/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/addon/admin//': RouteRecordInfo<'/addon/admin//', '/addon/admin', Record<never, never>, Record<never, never>>,
    '/addon/admin/403/403': RouteRecordInfo<'/addon/admin/403/403', '/addon/admin/403/403', Record<never, never>, Record<never, never>>,
    '/addon/admin/admin/': RouteRecordInfo<'/addon/admin/admin/', '/addon/admin/admin', Record<never, never>, Record<never, never>>,
    '/addon/admin/dict/': RouteRecordInfo<'/addon/admin/dict/', '/addon/admin/dict', Record<never, never>, Record<never, never>>,
    '/addon/admin/login/': RouteRecordInfo<'/addon/admin/login/', '/addon/admin/login', Record<never, never>, Record<never, never>>,
    '/addon/admin/menu/': RouteRecordInfo<'/addon/admin/menu/', '/addon/admin/menu', Record<never, never>, Record<never, never>>,
    '/addon/admin/news/detail/': RouteRecordInfo<'/addon/admin/news/detail/', '/addon/admin/news/detail', Record<never, never>, Record<never, never>>,
    '/addon/admin/news/detail/detail_2': RouteRecordInfo<'/addon/admin/news/detail/detail_2', '/addon/admin/news/detail/detail_2', Record<never, never>, Record<never, never>>,
    '/addon/admin/news/news': RouteRecordInfo<'/addon/admin/news/news', '/addon/admin/news/news', Record<never, never>, Record<never, never>>,
    '/addon/admin/role/': RouteRecordInfo<'/addon/admin/role/', '/addon/admin/role', Record<never, never>, Record<never, never>>,
    '/addon/admin/user/user': RouteRecordInfo<'/addon/admin/user/user', '/addon/admin/user/user', Record<never, never>, Record<never, never>>,
  }
}
