/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/internal//': RouteRecordInfo<'/internal//', '/internal', Record<never, never>, Record<never, never>>,
    '/internal//components/addonList': RouteRecordInfo<'/internal//components/addonList', '/internal/components/addonList', Record<never, never>, Record<never, never>>,
    '/internal//components/environmentInfo': RouteRecordInfo<'/internal//components/environmentInfo', '/internal/components/environmentInfo', Record<never, never>, Record<never, never>>,
    '/internal//components/operationLogs': RouteRecordInfo<'/internal//components/operationLogs', '/internal/components/operationLogs', Record<never, never>, Record<never, never>>,
    '/internal//components/performanceMetrics': RouteRecordInfo<'/internal//components/performanceMetrics', '/internal/components/performanceMetrics', Record<never, never>, Record<never, never>>,
    '/internal//components/quickActions': RouteRecordInfo<'/internal//components/quickActions', '/internal/components/quickActions', Record<never, never>, Record<never, never>>,
    '/internal//components/serviceStatus': RouteRecordInfo<'/internal//components/serviceStatus', '/internal/components/serviceStatus', Record<never, never>, Record<never, never>>,
    '/internal//components/systemNotifications': RouteRecordInfo<'/internal//components/systemNotifications', '/internal/components/systemNotifications', Record<never, never>, Record<never, never>>,
    '/internal//components/systemOverview': RouteRecordInfo<'/internal//components/systemOverview', '/internal/components/systemOverview', Record<never, never>, Record<never, never>>,
    '/internal//components/systemResources': RouteRecordInfo<'/internal//components/systemResources', '/internal/components/systemResources', Record<never, never>, Record<never, never>>,
    '/internal//components/userInfo': RouteRecordInfo<'/internal//components/userInfo', '/internal/components/userInfo', Record<never, never>, Record<never, never>>,
    '/internal/403/403': RouteRecordInfo<'/internal/403/403', '/internal/403/403', Record<never, never>, Record<never, never>>,
    '/internal/admin/': RouteRecordInfo<'/internal/admin/', '/internal/admin', Record<never, never>, Record<never, never>>,
    '/internal/admin/components/edit': RouteRecordInfo<'/internal/admin/components/edit', '/internal/admin/components/edit', Record<never, never>, Record<never, never>>,
    '/internal/admin/components/role': RouteRecordInfo<'/internal/admin/components/role', '/internal/admin/components/role', Record<never, never>, Record<never, never>>,
    '/internal/dict/': RouteRecordInfo<'/internal/dict/', '/internal/dict', Record<never, never>, Record<never, never>>,
    '/internal/dict/components/edit': RouteRecordInfo<'/internal/dict/components/edit', '/internal/dict/components/edit', Record<never, never>, Record<never, never>>,
    '/internal/login/components/emailLoginForm': RouteRecordInfo<'/internal/login/components/emailLoginForm', '/internal/login/components/emailLoginForm', Record<never, never>, Record<never, never>>,
    '/internal/login/components/registerForm': RouteRecordInfo<'/internal/login/components/registerForm', '/internal/login/components/registerForm', Record<never, never>, Record<never, never>>,
    '/internal/login/components/welcomePanel': RouteRecordInfo<'/internal/login/components/welcomePanel', '/internal/login/components/welcomePanel', Record<never, never>, Record<never, never>>,
    '/internal/login/index_1': RouteRecordInfo<'/internal/login/index_1', '/internal/login/index_1', Record<never, never>, Record<never, never>>,
    '/internal/menu/': RouteRecordInfo<'/internal/menu/', '/internal/menu', Record<never, never>, Record<never, never>>,
    '/internal/menu/components/edit': RouteRecordInfo<'/internal/menu/components/edit', '/internal/menu/components/edit', Record<never, never>, Record<never, never>>,
    '/internal/news/detail/': RouteRecordInfo<'/internal/news/detail/', '/internal/news/detail', Record<never, never>, Record<never, never>>,
    '/internal/news/detail/detail_2': RouteRecordInfo<'/internal/news/detail/detail_2', '/internal/news/detail/detail_2', Record<never, never>, Record<never, never>>,
    '/internal/news/news': RouteRecordInfo<'/internal/news/news', '/internal/news/news', Record<never, never>, Record<never, never>>,
    '/internal/role/': RouteRecordInfo<'/internal/role/', '/internal/role', Record<never, never>, Record<never, never>>,
    '/internal/role/components/api': RouteRecordInfo<'/internal/role/components/api', '/internal/role/components/api', Record<never, never>, Record<never, never>>,
    '/internal/role/components/edit': RouteRecordInfo<'/internal/role/components/edit', '/internal/role/components/edit', Record<never, never>, Record<never, never>>,
    '/internal/role/components/menu': RouteRecordInfo<'/internal/role/components/menu', '/internal/role/components/menu', Record<never, never>, Record<never, never>>,
    '/internal/user/user': RouteRecordInfo<'/internal/user/user', '/internal/user/user', Record<never, never>, Record<never, never>>,
  }
}
